// <auto-generated />
namespace TDLC.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class simplifica_remove_midia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(simplifica_remove_midia));
        
        string IMigrationMetadata.Id
        {
            get { return "201612231925465_simplifica_remove_midia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
