// <auto-generated />
namespace TDLC.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mudanca_campos2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mudanca_campos2));
        
        string IMigrationMetadata.Id
        {
            get { return "201612290157259_mudanca_campos2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
