// <auto-generated />
namespace TDLC.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class enderecotelefone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enderecotelefone));
        
        string IMigrationMetadata.Id
        {
            get { return "201712231947566_endereco-telefone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
